//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * A Work Breakdown Element and Work Definition which supports the nesting and logical grouping of related Breakdown Elements forming breakdown structures.  Although Activity is a concrete meta-class, other classes which represent breakdown structures derive from it; such as Phase, Iteration, Delivery Process, or Capability Pattern.
 * Activity represents a grouping element for other Breakdown Elements such as Activities, Descriptors, Milestones, etc.  It is not per-se a 'high-level' grouping of only work as in other meta-models, but groups any kind of Breakdown Elements.  For example, one can define valid Activities that group only Work Products Descriptors without any matching Task Descriptors.  Activities also inherit all properties from Work Breakdown Element and indirectly from Process Element; i.e. Activity is ready to have a full content description attached to it.
 * 
 * <p>Java class for Activity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Activity">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/epf/uma/1.0.3}WorkBreakdownElement">
 *       &lt;sequence>
 *         &lt;element name="Precondition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Postcondition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="BreakdownElement" type="{http://www.eclipse.org/epf/uma/1.0.3}BreakdownElement"/>
 *           &lt;element name="Checklist" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Concept" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Example" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Guideline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Roadmap" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="ReusableAsset" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="SupportingMaterial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Whitepaper" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="IsEnactable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="variabilityBasedOnElement" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="variabilityType" type="{http://www.eclipse.org/epf/uma/1.0.3}VariabilityType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Activity", propOrder = {
    "precondition",
    "postcondition",
    "breakdownElementOrChecklistOrConcept"
})
public class Activity
    extends WorkBreakdownElement
{

    @XmlElement(name = "Precondition")
    protected String precondition;
    @XmlElement(name = "Postcondition")
    protected String postcondition;
    @XmlElementRefs({
        @XmlElementRef(name = "Guideline", type = JAXBElement.class),
        @XmlElementRef(name = "Checklist", type = JAXBElement.class),
        @XmlElementRef(name = "BreakdownElement", type = JAXBElement.class),
        @XmlElementRef(name = "Roadmap", type = JAXBElement.class),
        @XmlElementRef(name = "Whitepaper", type = JAXBElement.class),
        @XmlElementRef(name = "ReusableAsset", type = JAXBElement.class),
        @XmlElementRef(name = "SupportingMaterial", type = JAXBElement.class),
        @XmlElementRef(name = "Example", type = JAXBElement.class),
        @XmlElementRef(name = "Concept", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> breakdownElementOrChecklistOrConcept;
    @XmlAttribute(name = "IsEnactable")
    protected Boolean isEnactable;
    @XmlAttribute
    protected String variabilityBasedOnElement;
    @XmlAttribute
    protected VariabilityType variabilityType;

    /**
     * Gets the value of the precondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecondition() {
        return precondition;
    }

    /**
     * Sets the value of the precondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecondition(String value) {
        this.precondition = value;
    }

    /**
     * Gets the value of the postcondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostcondition() {
        return postcondition;
    }

    /**
     * Sets the value of the postcondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostcondition(String value) {
        this.postcondition = value;
    }

    /**
     * Gets the value of the breakdownElementOrChecklistOrConcept property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the breakdownElementOrChecklistOrConcept property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBreakdownElementOrChecklistOrConcept().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BreakdownElement }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getBreakdownElementOrChecklistOrConcept() {
        if (breakdownElementOrChecklistOrConcept == null) {
            breakdownElementOrChecklistOrConcept = new ArrayList<JAXBElement<?>>();
        }
        return this.breakdownElementOrChecklistOrConcept;
    }

    /**
     * Gets the value of the isEnactable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEnactable() {
        return isEnactable;
    }

    /**
     * Sets the value of the isEnactable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEnactable(Boolean value) {
        this.isEnactable = value;
    }

    /**
     * Gets the value of the variabilityBasedOnElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariabilityBasedOnElement() {
        return variabilityBasedOnElement;
    }

    /**
     * Sets the value of the variabilityBasedOnElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariabilityBasedOnElement(String value) {
        this.variabilityBasedOnElement = value;
    }

    /**
     * Gets the value of the variabilityType property.
     * 
     * @return
     *     possible object is
     *     {@link VariabilityType }
     *     
     */
    public VariabilityType getVariabilityType() {
        return variabilityType;
    }

    /**
     * Sets the value of the variabilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariabilityType }
     *     
     */
    public void setVariabilityType(VariabilityType value) {
        this.variabilityType = value;
    }

}
