//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * A Describable Element that represents an abstract generalization for all elements that are considered to be and managed as Method Content.
 * Content Elements represents reusable Method Content that is supposed to be managed in Content Packages.  The separation of Content Element from Process Element allows to clearly distinguish between pure method content from content that is represented in processes.
 * 
 * <p>Java class for ContentElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/epf/uma/1.0.3}DescribableElement">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="Checklist" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Concept" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Example" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Guideline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="ReusableAsset" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="SupportingMaterial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Whitepaper" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="variabilityBasedOnElement" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="variabilityType" type="{http://www.eclipse.org/epf/uma/1.0.3}VariabilityType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentElement", propOrder = {
    "checklistOrConceptOrExample"
})
public class ContentElement
    extends DescribableElement
{

    @XmlElementRefs({
        @XmlElementRef(name = "Whitepaper", type = JAXBElement.class),
        @XmlElementRef(name = "Concept", type = JAXBElement.class),
        @XmlElementRef(name = "ReusableAsset", type = JAXBElement.class),
        @XmlElementRef(name = "Example", type = JAXBElement.class),
        @XmlElementRef(name = "Guideline", type = JAXBElement.class),
        @XmlElementRef(name = "Checklist", type = JAXBElement.class),
        @XmlElementRef(name = "SupportingMaterial", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> checklistOrConceptOrExample;
    @XmlAttribute
    protected String variabilityBasedOnElement;
    @XmlAttribute
    protected VariabilityType variabilityType;

    /**
     * Gets the value of the checklistOrConceptOrExample property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the checklistOrConceptOrExample property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChecklistOrConceptOrExample().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getChecklistOrConceptOrExample() {
        if (checklistOrConceptOrExample == null) {
            checklistOrConceptOrExample = new ArrayList<JAXBElement<String>>();
        }
        return this.checklistOrConceptOrExample;
    }

    /**
     * Gets the value of the variabilityBasedOnElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariabilityBasedOnElement() {
        return variabilityBasedOnElement;
    }

    /**
     * Sets the value of the variabilityBasedOnElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariabilityBasedOnElement(String value) {
        this.variabilityBasedOnElement = value;
    }

    /**
     * Gets the value of the variabilityType property.
     * 
     * @return
     *     possible object is
     *     {@link VariabilityType }
     *     
     */
    public VariabilityType getVariabilityType() {
        return variabilityType;
    }

    /**
     * Sets the value of the variabilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariabilityType }
     *     
     */
    public void setVariabilityType(VariabilityType value) {
        this.variabilityType = value;
    }

}
