//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * A specific type of guidance that represents a proven way or strategy of doing work to achieve a goal that has a positive impact on work product or process quality.  Practices are defined orthogonal to methods and processes.  They could summarize aspects that impact many different parts of a method or specific processes.  Examples for practices would be "Manage Risks", "Continuously verify quality", "Architecture-centric and component-based development", etc.
 * 
 * <p>Java class for Practice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Practice">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/epf/uma/1.0.3}Guidance">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="ActivityReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContentReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubPractice" type="{http://www.eclipse.org/epf/uma/1.0.3}Practice"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Practice", propOrder = {
    "activityReferenceOrContentReferenceOrSubPractice"
})
public class Practice
    extends Guidance
{

    @XmlElementRefs({
        @XmlElementRef(name = "ContentReference", type = JAXBElement.class),
        @XmlElementRef(name = "ActivityReference", type = JAXBElement.class),
        @XmlElementRef(name = "SubPractice", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> activityReferenceOrContentReferenceOrSubPractice;

    /**
     * Gets the value of the activityReferenceOrContentReferenceOrSubPractice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activityReferenceOrContentReferenceOrSubPractice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivityReferenceOrContentReferenceOrSubPractice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Practice }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getActivityReferenceOrContentReferenceOrSubPractice() {
        if (activityReferenceOrContentReferenceOrSubPractice == null) {
            activityReferenceOrContentReferenceOrSubPractice = new ArrayList<JAXBElement<?>>();
        }
        return this.activityReferenceOrContentReferenceOrSubPractice;
    }

}
