//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for WorkOrderType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WorkOrderType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *     &lt;enumeration value="finishToStart"/>
 *     &lt;enumeration value="finishToFinish"/>
 *     &lt;enumeration value="startToStart"/>
 *     &lt;enumeration value="startToFinish"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum WorkOrderType {

    @XmlEnumValue("finishToFinish")
    FINISH_TO_FINISH("finishToFinish"),
    @XmlEnumValue("finishToStart")
    FINISH_TO_START("finishToStart"),
    @XmlEnumValue("startToFinish")
    START_TO_FINISH("startToFinish"),
    @XmlEnumValue("startToStart")
    START_TO_START("startToStart");
    private final String value;

    WorkOrderType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WorkOrderType fromValue(String v) {
        for (WorkOrderType c: WorkOrderType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
