//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A generalized Work Product Description that is used to store the textual description for an Artifact.
 * 
 * <p>Java class for ArtifactDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArtifactDescription">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/epf/uma/1.0.3}WorkProductDescription">
 *       &lt;sequence>
 *         &lt;element name="BriefOutline" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RepresentationOptions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArtifactDescription", propOrder = {
    "briefOutline",
    "representationOptions"
})
public class ArtifactDescription
    extends WorkProductDescription
{

    @XmlElement(name = "BriefOutline")
    protected String briefOutline;
    @XmlElement(name = "RepresentationOptions")
    protected String representationOptions;

    /**
     * Gets the value of the briefOutline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBriefOutline() {
        return briefOutline;
    }

    /**
     * Sets the value of the briefOutline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBriefOutline(String value) {
        this.briefOutline = value;
    }

    /**
     * Gets the value of the representationOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentationOptions() {
        return representationOptions;
    }

    /**
     * Sets the value of the representationOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentationOptions(String value) {
        this.representationOptions = value;
    }

}
