//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * An abstract generalization for any type of Method Element that is part of a breakdown structure.  It defines a set of properties available to all of its specializations.
 * 
 * <p>Java class for BreakdownElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BreakdownElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/epf/uma/1.0.3}ProcessElement">
 *       &lt;sequence>
 *         &lt;element name="PresentedAfter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PresentedBefore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PlanningData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SuperActivity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="hasMultipleOccurrences" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isOptional" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isPlanned" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="prefix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BreakdownElement", propOrder = {
    "presentedAfter",
    "presentedBefore",
    "planningData",
    "superActivity"
})
public class BreakdownElement
    extends ProcessElement
{

    @XmlElement(name = "PresentedAfter")
    protected String presentedAfter;
    @XmlElement(name = "PresentedBefore")
    protected String presentedBefore;
    @XmlElement(name = "PlanningData")
    protected String planningData;
    @XmlElement(name = "SuperActivity")
    protected String superActivity;
    @XmlAttribute
    protected Boolean hasMultipleOccurrences;
    @XmlAttribute
    protected Boolean isOptional;
    @XmlAttribute
    protected Boolean isPlanned;
    @XmlAttribute
    protected String prefix;

    /**
     * Gets the value of the presentedAfter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentedAfter() {
        return presentedAfter;
    }

    /**
     * Sets the value of the presentedAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentedAfter(String value) {
        this.presentedAfter = value;
    }

    /**
     * Gets the value of the presentedBefore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentedBefore() {
        return presentedBefore;
    }

    /**
     * Sets the value of the presentedBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentedBefore(String value) {
        this.presentedBefore = value;
    }

    /**
     * Gets the value of the planningData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanningData() {
        return planningData;
    }

    /**
     * Sets the value of the planningData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanningData(String value) {
        this.planningData = value;
    }

    /**
     * Gets the value of the superActivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuperActivity() {
        return superActivity;
    }

    /**
     * Sets the value of the superActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuperActivity(String value) {
        this.superActivity = value;
    }

    /**
     * Gets the value of the hasMultipleOccurrences property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasMultipleOccurrences() {
        return hasMultipleOccurrences;
    }

    /**
     * Sets the value of the hasMultipleOccurrences property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasMultipleOccurrences(Boolean value) {
        this.hasMultipleOccurrences = value;
    }

    /**
     * Gets the value of the isOptional property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsOptional() {
        return isOptional;
    }

    /**
     * Sets the value of the isOptional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsOptional(Boolean value) {
        this.isOptional = value;
    }

    /**
     * Gets the value of the isPlanned property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPlanned() {
        return isPlanned;
    }

    /**
     * Sets the value of the isPlanned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPlanned(Boolean value) {
        this.isPlanned = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

}
