//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A special Method Package that only contains Content Category Elements.
 * 
 * <p>Java class for ContentCategoryPackage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentCategoryPackage">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/epf/uma/1.0.3}MethodPackage">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="ContentCategory" type="{http://www.eclipse.org/epf/uma/1.0.3}ContentCategory"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentCategoryPackage", propOrder = {
    "contentCategory"
})
public class ContentCategoryPackage
    extends MethodPackage
{

    @XmlElement(name = "ContentCategory", required = true)
    protected List<ContentCategory> contentCategory;

    /**
     * Gets the value of the contentCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContentCategory }
     * 
     * 
     */
    public List<ContentCategory> getContentCategory() {
        if (contentCategory == null) {
            contentCategory = new ArrayList<ContentCategory>();
        }
        return this.contentCategory;
    }

}
