//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A generalized Breakdown Element Description that is used to store the textual description for a Descriptor.
 * 
 * <p>Java class for DescriptorDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescriptorDescription">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/epf/uma/1.0.3}BreakdownElementDescription">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="RefinedDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescriptorDescription", propOrder = {
    "refinedDescription"
})
public class DescriptorDescription
    extends BreakdownElementDescription
{

    @XmlElement(name = "RefinedDescription")
    protected String refinedDescription;

    /**
     * Gets the value of the refinedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefinedDescription() {
        return refinedDescription;
    }

    /**
     * Sets the value of the refinedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefinedDescription(String value) {
        this.refinedDescription = value;
    }

}
