//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The root generalization for all UMA Method Elements.  Defines a common set of attributes inherited by all UMA Method Elements.  Method Element itself is derived from Packageable Element from the UML 2.0 Infrastructure.
 * 
 * <p>Java class for MethodElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MethodElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/epf/uma/1.0.3}PackageableElement">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="OwnedRule" type="{http://www.eclipse.org/epf/uma/1.0.3}Constraint"/>
 *       &lt;/choice>
 *       &lt;attribute name="briefDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orderingGuide" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="suppressed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MethodElement", propOrder = {
    "ownedRule"
})
public class MethodElement
    extends PackageableElement
{

    @XmlElement(name = "OwnedRule", required = true)
    protected List<Constraint> ownedRule;
    @XmlAttribute
    protected String briefDescription;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String orderingGuide;
    @XmlAttribute
    protected Boolean suppressed;

    /**
     * Gets the value of the ownedRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ownedRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwnedRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Constraint }
     * 
     * 
     */
    public List<Constraint> getOwnedRule() {
        if (ownedRule == null) {
            ownedRule = new ArrayList<Constraint>();
        }
        return this.ownedRule;
    }

    /**
     * Gets the value of the briefDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBriefDescription() {
        return briefDescription;
    }

    /**
     * Sets the value of the briefDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBriefDescription(String value) {
        this.briefDescription = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the orderingGuide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingGuide() {
        return orderingGuide;
    }

    /**
     * Sets the value of the orderingGuide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingGuide(String value) {
        this.orderingGuide = value;
    }

    /**
     * Gets the value of the suppressed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSuppressed() {
        return suppressed;
    }

    /**
     * Sets the value of the suppressed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSuppressed(Boolean value) {
        this.suppressed = value;
    }

}
