//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A collection of selected Method Models and MethodPackages. A configuration can be exported into its own standalone library when it includes the full transitive closure of all elements all other elements depend on.
 * 
 * <p>Java class for MethodConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MethodConfiguration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/epf/uma/1.0.3}MethodUnit">
 *       &lt;sequence>
 *         &lt;element name="BaseConfiguration" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MethodPluginSelection" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MethodPackageSelection" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DefaultView" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProcessView" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MethodConfiguration", propOrder = {
    "baseConfiguration",
    "methodPluginSelection",
    "methodPackageSelection",
    "defaultView",
    "processView"
})
public class MethodConfiguration
    extends MethodUnit
{

    @XmlElement(name = "BaseConfiguration", required = true)
    protected List<String> baseConfiguration;
    @XmlElement(name = "MethodPluginSelection", required = true)
    protected List<String> methodPluginSelection;
    @XmlElement(name = "MethodPackageSelection", required = true)
    protected List<String> methodPackageSelection;
    @XmlElement(name = "DefaultView")
    protected String defaultView;
    @XmlElement(name = "ProcessView", required = true)
    protected List<String> processView;

    /**
     * Gets the value of the baseConfiguration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baseConfiguration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaseConfiguration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBaseConfiguration() {
        if (baseConfiguration == null) {
            baseConfiguration = new ArrayList<String>();
        }
        return this.baseConfiguration;
    }

    /**
     * Gets the value of the methodPluginSelection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the methodPluginSelection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMethodPluginSelection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMethodPluginSelection() {
        if (methodPluginSelection == null) {
            methodPluginSelection = new ArrayList<String>();
        }
        return this.methodPluginSelection;
    }

    /**
     * Gets the value of the methodPackageSelection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the methodPackageSelection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMethodPackageSelection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMethodPackageSelection() {
        if (methodPackageSelection == null) {
            methodPackageSelection = new ArrayList<String>();
        }
        return this.methodPackageSelection;
    }

    /**
     * Gets the value of the defaultView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultView() {
        return defaultView;
    }

    /**
     * Sets the value of the defaultView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultView(String value) {
        this.defaultView = value;
    }

    /**
     * Gets the value of the processView property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processView property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessView().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProcessView() {
        if (processView == null) {
            processView = new ArrayList<String>();
        }
        return this.processView;
    }

}
