//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.eclipse.org/epf/uma/1.0.3")
package org.eclipse.epf.uma._1_0;
