//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for VariabilityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VariabilityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *     &lt;enumeration value="na"/>
 *     &lt;enumeration value="contributes"/>
 *     &lt;enumeration value="extends"/>
 *     &lt;enumeration value="replaces"/>
 *     &lt;enumeration value="localContribution"/>
 *     &lt;enumeration value="localReplacement"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum VariabilityType {

    @XmlEnumValue("contributes")
    CONTRIBUTES("contributes"),
    @XmlEnumValue("extends")
    EXTENDS("extends"),
    @XmlEnumValue("localContribution")
    LOCAL_CONTRIBUTION("localContribution"),
    @XmlEnumValue("localReplacement")
    LOCAL_REPLACEMENT("localReplacement"),
    @XmlEnumValue("na")
    NA("na"),
    @XmlEnumValue("replaces")
    REPLACES("replaces");
    private final String value;

    VariabilityType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VariabilityType fromValue(String v) {
        for (VariabilityType c: VariabilityType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
