//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * A special Descriptor that represents a Work Product in the context of one specific Activity.  Every breakdown structure can define different relationships of Work Product Descriptors to Task Descriptors and Role Descriptors.  Therefore one Work Product can be represented by many Work Product Descriptors each within the context of an Activity with its own set of relationships.
 * 
 * <p>Java class for WorkProductDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkProductDescriptor">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/epf/uma/1.0.3}Descriptor">
 *       &lt;sequence>
 *         &lt;element name="WorkProduct" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResponsibleRole" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="ExternalInputTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="ImpactedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Impacts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="MandatoryInputTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="OptionalInputTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="OutputFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="DeliverableParts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="activityEntryState" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="activityExitState" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkProductDescriptor", propOrder = {
    "workProduct",
    "responsibleRole",
    "externalInputToOrImpactedByOrImpacts"
})
public class WorkProductDescriptor
    extends Descriptor
{

    @XmlElement(name = "WorkProduct")
    protected String workProduct;
    @XmlElement(name = "ResponsibleRole")
    protected String responsibleRole;
    @XmlElementRefs({
        @XmlElementRef(name = "OptionalInputTo", type = JAXBElement.class),
        @XmlElementRef(name = "ImpactedBy", type = JAXBElement.class),
        @XmlElementRef(name = "ExternalInputTo", type = JAXBElement.class),
        @XmlElementRef(name = "DeliverableParts", type = JAXBElement.class),
        @XmlElementRef(name = "MandatoryInputTo", type = JAXBElement.class),
        @XmlElementRef(name = "OutputFrom", type = JAXBElement.class),
        @XmlElementRef(name = "Impacts", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> externalInputToOrImpactedByOrImpacts;
    @XmlAttribute
    protected String activityEntryState;
    @XmlAttribute
    protected String activityExitState;

    /**
     * Gets the value of the workProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkProduct() {
        return workProduct;
    }

    /**
     * Sets the value of the workProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkProduct(String value) {
        this.workProduct = value;
    }

    /**
     * Gets the value of the responsibleRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsibleRole() {
        return responsibleRole;
    }

    /**
     * Sets the value of the responsibleRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsibleRole(String value) {
        this.responsibleRole = value;
    }

    /**
     * Gets the value of the externalInputToOrImpactedByOrImpacts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalInputToOrImpactedByOrImpacts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalInputToOrImpactedByOrImpacts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getExternalInputToOrImpactedByOrImpacts() {
        if (externalInputToOrImpactedByOrImpacts == null) {
            externalInputToOrImpactedByOrImpacts = new ArrayList<JAXBElement<String>>();
        }
        return this.externalInputToOrImpactedByOrImpacts;
    }

    /**
     * Gets the value of the activityEntryState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityEntryState() {
        return activityEntryState;
    }

    /**
     * Sets the value of the activityEntryState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityEntryState(String value) {
        this.activityEntryState = value;
    }

    /**
     * Gets the value of the activityExitState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityExitState() {
        return activityExitState;
    }

    /**
     * Sets the value of the activityExitState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityExitState(String value) {
        this.activityExitState = value;
    }

}
