//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A generalized Content Description that is used to store the textual description for a Work Product.
 * 
 * <p>Java class for WorkProductDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkProductDescription">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/epf/uma/1.0.3}ContentDescription">
 *       &lt;sequence>
 *         &lt;element name="ImpactOfNotHaving" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Purpose" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReasonsForNotNeeding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="externalId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkProductDescription", propOrder = {
    "impactOfNotHaving",
    "purpose",
    "reasonsForNotNeeding"
})
public class WorkProductDescription
    extends ContentDescription
{

    @XmlElement(name = "ImpactOfNotHaving")
    protected String impactOfNotHaving;
    @XmlElement(name = "Purpose")
    protected String purpose;
    @XmlElement(name = "ReasonsForNotNeeding")
    protected String reasonsForNotNeeding;
    @XmlAttribute
    protected String externalId;

    /**
     * Gets the value of the impactOfNotHaving property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpactOfNotHaving() {
        return impactOfNotHaving;
    }

    /**
     * Sets the value of the impactOfNotHaving property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpactOfNotHaving(String value) {
        this.impactOfNotHaving = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the reasonsForNotNeeding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonsForNotNeeding() {
        return reasonsForNotNeeding;
    }

    /**
     * Sets the value of the reasonsForNotNeeding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonsForNotNeeding(String value) {
        this.reasonsForNotNeeding = value;
    }

    /**
     * Gets the value of the externalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalId() {
        return externalId;
    }

    /**
     * Sets the value of the externalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalId(String value) {
        this.externalId = value;
    }

}
