//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 03:11:12 PM CEST 
//


package org.eclipse.epf.uma._1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A special Breakdown Element that provides specific properties for Breakdown Elements that represent or refer to Work Definitions.  For example its subclass Activity defines work as it is also a subclass of Work Definition.  Its subclass Task Descriptor does not define work by itself, but refers to a Work Definition and therefore can have the same common properties and Work Breakdown Element has.
 * 
 * <p>Java class for WorkBreakdownElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkBreakdownElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/epf/uma/1.0.3}BreakdownElement">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Predecessor" type="{http://www.eclipse.org/epf/uma/1.0.3}WorkOrder"/>
 *       &lt;/choice>
 *       &lt;attribute name="isEventDriven" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isOngoing" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isRepeatable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkBreakdownElement", propOrder = {
    "predecessor"
})
public class WorkBreakdownElement
    extends BreakdownElement
{

    @XmlElement(name = "Predecessor", required = true)
    protected List<WorkOrder> predecessor;
    @XmlAttribute
    protected Boolean isEventDriven;
    @XmlAttribute
    protected Boolean isOngoing;
    @XmlAttribute
    protected Boolean isRepeatable;

    /**
     * Gets the value of the predecessor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the predecessor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPredecessor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkOrder }
     * 
     * 
     */
    public List<WorkOrder> getPredecessor() {
        if (predecessor == null) {
            predecessor = new ArrayList<WorkOrder>();
        }
        return this.predecessor;
    }

    /**
     * Gets the value of the isEventDriven property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEventDriven() {
        return isEventDriven;
    }

    /**
     * Sets the value of the isEventDriven property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEventDriven(Boolean value) {
        this.isEventDriven = value;
    }

    /**
     * Gets the value of the isOngoing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsOngoing() {
        return isOngoing;
    }

    /**
     * Sets the value of the isOngoing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsOngoing(Boolean value) {
        this.isOngoing = value;
    }

    /**
     * Gets the value of the isRepeatable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRepeatable() {
        return isRepeatable;
    }

    /**
     * Sets the value of the isRepeatable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRepeatable(Boolean value) {
        this.isRepeatable = value;
    }

}
